name: batteries
description: >
  A set of typical classes, extensions and utilities for dart and flutter that help in development.
version: 0.0.1-beta
repository: https://github.com/PlugFox/batteries
issue_tracker: https://github.com/PlugFox/batteries/issues
homepage: https://github.com/PlugFox/batteries
#publish_to: https://pub.dev
#documentation: https://pub.dev/documentation/batteries/latest/
#authors:
#  - Plague Fox <plugfox@gmail.com>

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.8
  mockito: ^5.1.0
  coverage: ^1.2.0
  test: ^1.20.2
  grinder: ^0.9.1

#dependency_overrides:

#executables:
