name: batteries
description: >
  A set of typical classes, extensions and utilities for dart and flutter that help in development.
version: 0.1.0-dev
repository: https://github.com/PlugFox/batteries
issue_tracker: https://github.com/PlugFox/batteries/issues
homepage: https://github.com/PlugFox/batteries
#publish_to: https://pub.dev
#documentation: https://pub.dev/documentation/batteries/latest/
#authors:
#  - Plague Fox <plugfox@gmail.com>

funding:
  - https://www.buymeacoffee.com/plugfox
  - https://www.patreon.com/plugfox
  - https://boosty.to/plugfox

topics:
  - utilities
  - batteries
  - helpers
  - extensions
  - transformers

#screenshots:
#  - description: 'Example of using the library'
#    path: example.png

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  # Annotations
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.6
  benchmark_harness: ^2.2.2
  lints: ">=4.0.0 <6.0.0"
  mockito: ^5.1.0
  test: ^1.24.4
  fake_async: ^1.3.1
