name: flutter_batteries_example
version: 0.0.0+1
repository: https://github.com/PlugFox/batteries
issue_tracker: https://github.com/PlugFox/batteries/issues
homepage: https://github.com/PlugFox/batteries
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  flutter_batteries:
    path: ../

dev_dependency:
  flutter_lints: any
