name: CHECKOUT

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'support/**'
    paths:
      - 'lib/**.dart'
      - 'test/**.dart'
      - 'example/**.dart'
  pull_request:
    branches:
      - 'master'
      - 'develop'
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'support/**'
    paths:
      - 'lib/**.dart'
      - 'test/**.dart'
      - 'example/**.dart'

jobs:
  checkout:
    runs-on: ubuntu-latest
    container:
      image: dart:beta
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install Dependencies
        run: dart pub get
        timeout-minutes: 1
      - name: Check format
        run: dart format --set-exit-if-changed -l 80 -o none .
        timeout-minutes: 1
      - name: Check analyzer
        run: dart analyze --fatal-infos --fatal-warnings lib
        timeout-minutes: 1
      #- name: Check with pana
      #  run: dart pub global activate pana && pana --json --no-warning --line-length 80
      - name: Run tests
        run: dart test --concurrency=6 --platform vm --coverage=coverage test/
        timeout-minutes: 3
      - name: Collect coverage
        run: dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib
        timeout-minutes: 1
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        timeout-minutes: 1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.1
        timeout-minutes: 1
        with:
          path: coverage/lcov.info
          min_coverage: 90
          #exclude: '**.g.dart **.freezed.dart'